### ISSUE TITLE
Current `master` cannot be build/run due to inconsistent database scheme

### ISSUE THREAD

**Issue by bentolor** [diva-e/Techradar#28]
Thanks for publishing your work. 

I'm trying to run/build your techradar version but stumble upon a set of issues:

* The installation/instruction seems to be no longer in sync with the actual requirements. I figured out that I need to create a `backend/.env` file and copy `./frontend/src/environments/environment.ts`
* The docker-compose does produce an empty app-container missing the source
* most of the left-out credentials are visible/hard-coded in some places elsewhere. Except for the `environment.prod.ts` which introduces a hostname I do not see why the publish version should not have a pre-configured state running as localhost.
* After fixing all these issues the applications runs but fails on creating any new entries due to the database scheme not being up-to-date.  Also applying the rather mysterious `migratePersons` or `upgrade` would not fix this issue.

What are the current plans on this project: Is it actively worked on? If not: What would be a best-working start to start off?

This is the console output I receive
````
Error:  QueryFailedError: Field 'Contact' doesn't have a default value
    at new QueryFailedError (/diva-e-techradar.git/backend/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.onResult (/diva-e-techradar.git/backend/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:170:45)
    at Query.execute (/diva-e-techradar.git/backend/node_modules/mysql2/lib/commands/command.js:30:14)
    at PoolConnection.handlePacket (/diva-e-techradar.git/backend/node_modules/mysql2/lib/connection.js:408:32)
    at PacketParser.onPacket (/diva-e-techradar.git/backend/node_modules/mysql2/lib/connection.js:70:12)
    at PacketParser.executeStart (/diva-e-techradar.git/backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/diva-e-techradar.git/backend/node_modules/mysql2/lib/connection.js:77:25)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlState: 'HY000',
  sqlMessage: "Field 'Contact' doesn't have a default value",
  query: 'INSERT INTO `project_technologies`(`TechnologyName`, `ProjectName`, `Description`, `Link`, `Created`, `LastUpdated`, `Sector`, `Maturity`, `id`) VALUES (?, ?, ?, ?, DEFAULT, DEFAULT, ?, ?, DEFAULT)',
  parameters: [ 'a', 'a', 'aaa', '', 0, 0 ]
}
(node:3697) UnhandledPromiseRejectionWarning: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
    at ServerResponse.writeHead (_http_server.js:248:11)
    at ServerResponse._implicitHeader (_http_server.js:239:8)
    at write_ (_http_outgoing.js:650:9)
    at ServerResponse.end (_http_outgoing.js:761:5)
    at ServerResponse.send (/diva-e-techradar.git/backend/node_modules/express/lib/response.js:221:10)
    at ServerResponse.json (/diva-e-techradar.git/backend/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/diva-e-techradar.git/backend/node_modules/express/lib/response.js:158:21)
    at Object.<anonymous> (/diva-e-techradar.git/backend/dist/out-tsc/routes/routes.js:27:18)
    at Generator.throw (<anonymous>)
    at rejected (/diva-e-techradar.git/backend/dist/out-tsc/routes/routes.js:6:65)
(node:3697) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3697) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

**Comment by nstuder** [comment]
I'm sorry this Repository is no longer actively maintained. 
I have pushed new changes, so that it should run normally.
